### ISSUE TITLE
Rails 5 and Authem

### ISSUE THREAD

**Issue by plicjo** [paulelliott/authem#28]
I installed Authem on a Rails 5 beta application.

It installed version 1.5. `bundle update` didn't upgrade it to 2.0 either. Is this due to Authem's dependencies? Am I retarded? Please advise.

**Comment by plicjo** [comment]
When I explicitly require Authem 2.0.1:

```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    authem (~> 2.0.1) was resolved to 2.0.1, which depends on
      railties (~> 4.0)

    coffee-rails (~> 4.1.0) was resolved to 4.1.1, which depends on
      railties (< 5.1.x, >= 4.0.0)

    jquery-rails was resolved to 4.1.0, which depends on
      railties (>= 4.2.0)

    rails (< 5.1, >= 5.0.0.beta3) was resolved to 5.0.0.beta3, which depends on
      railties (= 5.0.0.beta3)

    rspec-rails was resolved to 3.1.0, which depends on
      railties (>= 3.0)

    sass-rails (~> 5.0) was resolved to 5.0.4, which depends on
      railties (< 5.0, >= 4.0.0)

    web-console (~> 3.0) was resolved to 3.1.1, which depends on
      railties (>= 4.2)
```

**Comment by paulelliott** [comment]
Point at master and try it now. Should work for you.

**Comment by plicjo** [comment]
Thanks Paul!

**Comment by paulelliott** [comment]
If there are no other rails 5 issues let me know and I'll cut a release.

**Comment by plicjo** [comment]
Pointing at master, I installed Authem successfully on a Rails 5.0.0.beta3 application @ https://github.com/plicjo/rails_5_authem

I created a user and reset their password successfully in the console.

**Comment by paulelliott** [comment]
Awesome. I cut version 2.1.0 with these changes. Thanks!
